# Generated by Django 5.1 on 2024-08-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0002_alter_note_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.TextField(unique=True),
        ),
    ]
